on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd...
          zip -r app.ipa Payload
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: IPA
          path: build/ios/iphoneos/app.ipa

  unzip-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Download IPA Artifact
      uses: actions/download-artifact@v3
      with:
        name: IPA
        path: build/ios/iphoneos/app.ipa

    - name: Unzip IPA Artifact
      run: |
        unzip -o build/ios/iphoneos/app.ipa -d unziped_artifact
# push to master, main, develop
# pull request on main master
